#!/usr/bin/env bash
# This script displays the PID, along with the process nameof processes whose name contain the word bash

pids=$(pgrep -f bash)

for pid in $pids; do
    p_name=$(cat /proc/$pid/cmdline | tr '\0' ' ')
    echo "PID: $pid, Process Name: $p_name"
done

